In [1]:
from datasets import load_dataset

dataset = load_dataset("Qdrant/dbpedia-entities-openai3-text-embedding-3-large-3072-100K")

/Users/jperales/Documents/dev/vector-search-cost-efficient/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import pandas as pd

df = dataset["train"].to_pandas()

display(df)

,_id,title,text,text-embedding-3-large-3072-embedding
0,<dbpedia:Parabolic_reflector>,Parabolic reflector,A parabolic (or paraboloid or paraboloidal) re...,"[-0.022388368844985962, 0.028537113219499588, ..."
1,<dbpedia:John_Baird_(Canadian_politician)>,John Baird (Canadian politician),"John Russell Baird, PC (born May 26, 1969) ser...","[-0.009061033837497234, -0.011508856900036335,..."
2,<dbpedia:The_80s:_A_Look_Back_at_the_Tumultuou...,The 80s: A Look Back at the Tumultuous Decade ...,The 80s: A Look Back at the Tumultuous Decade ...,"[-0.0062423343770205975, -0.003029682207852602..."
3,<dbpedia:Shin_Sang-ok>,Shin Sang-ok,"Shin Sang-ok (October 18, 1926 – April 11, 200...","[0.03381354734301567, -0.006916407495737076, -..."
4,<dbpedia:Géza_Anda>,Géza Anda,Géza Anda (Hungarian pronunciation: [ˈɡeːzɒ ˈɒ...,"[-0.013956013135612011, 0.007346394006162882, ..."
...,...,...,...,...
99995,<dbpedia:Middlesex_(novel)>,Middlesex (novel),Middlesex is a Pulitzer Prize-winning novel by...,"[-0.006443378981202841, 0.02575031667947769, -..."
99996,"<dbpedia:Münster,_Hesse>","Münster, Hesse",Münster is a municipality in the district of D...,"[0.034265510737895966, 0.05587460845708847, -0..."
99997,<dbpedia:Cinemathique>,Cinemathique,Cinemathique is the third album by collaborati...,"[-0.0007967259734869003, -0.025265803560614586..."
99998,<dbpedia:Somatic_(biology)>,Somatic (biology),The term somatic is often used in biology to r...,"[0.013289892114698887, 0.006013763602823019, -..."
99999,<dbpedia:Matías_Silvestre>,Matías Silvestre,Matías Agustín Silvestre (born 25 September 19...,"[0.004791264422237873, 0.012086919508874416, -..."

In [3]:
import nltk

nltk.download('punkt')

[nltk_data] Downloading package punkt to /Users/jperales/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [11]:
from nltk.tokenize import word_tokenize

from collections import Counter

df["unigrams"] = df["text"].apply(lambda x: word_tokenize(x))

all_unigrams = [unigram for sublist in df['unigrams'] for unigram in sublist]

unigram_counts = Counter(all_unigrams)

# Convert the counts to a DataFrame
unigram_counts_df = pd.DataFrame(unigram_counts.items(), columns=['unigram', 'count'])

# Print the resulting DataFrame
print(unigram_counts_df.sort_values(by="count"))

                   unigram   count
161628  Ри́мский-Ко́рсаков       1
209857             1973.As       1
209858             1967.He       1
209859           Trautwine       1
209860             Espinel       1
...                    ...     ...
71                      in  157589
30                      of  210205
26                       .  244591
33                     the  305555
22                       ,  323985

[323258 rows x 2 columns]

In [22]:
# looking at the DF in data viewer, this cut off seemed reasonable

display(unigram_counts_df[unigram_counts_df["count"] < 12501].sort_values(by="count"))

                unigram  count
323257  tissue-specific      1
159007            6,853      1
258636    Strongstry.It      1
159010             WUAG      1
159011              JVM      1
...                 ...    ...
346               first  10661
198                   ;  10686
151                   –  11110
558            American  11290
699              United  11898

[323221 rows x 2 columns]